/**
 * TypeScript mirror of the backend Pydantic models in
 * `src/models/*.py`. Field names and nullability intentionally match
 * the Python source exactly — this file is generated by hand from
 * that source of truth and should be kept in sync with it, not
 * redesigned independently.
 */

/** src/models/maternal.py :: MaternalData */
export interface MaternalData {
  mother_name: string | null
  father_name: string | null
  mother_age: number | null
  hospital_name: string | null
  hospital_reg_no: string | null
  baby_uid: string | null
  gestational_age: string | null
  delivery_type: string | null
  labour_type: string | null
  maternal_remarks: string | null

  gravida: number | null
  para: number | null

  corticosteroids_given: boolean | null
  steroid_type: string | null
  steroid_doses: number | null

  fever_history: string | null
  foul_smelling_discharge: boolean | null
  uterine_tenderness: boolean | null
  pprom_over_24h: boolean | null
  amniotic_fluid_appearance: string | null
  presentation: string | null
  labour_course: string | null
  foetal_distress: boolean | null
  delivery_mode: string | null
  delivery_attendant: string | null
  significant_maternal_info_flag: boolean | null

  blood_group: string | null
  vdrl: string | null
  hbsag: string | null
  hiv_status: string | null
  pih: boolean | null
  gdm: boolean | null
  thyroid_status: string | null
  oligohydramnios: boolean | null
  amniotic_fluid_volume: string | null
  illness_history: string | null
  epilepsy_radiation_drug_history: string | null
  aph: boolean | null
}

/** src/models/dcm.py :: DCMData (Daily Clinical Monitoring) */
export interface DCMData {
  monitoring_date: string | null
  vital_status: string | null
  discharged_or_referred: boolean | null
  bed_sharing: boolean | null

  weight_taken: boolean | null
  weight: number | null
  weight_not_taken_reason: string | null

  on_incubator_support: boolean | null
  on_medications: boolean | null
  medications: string | null

  kmc_provided: boolean | null
  kmc_not_provided_reason: string | null

  feed_types: string | null
  feed_route: string | null
  enteral_feed_ml: number | null
  tpn_ml: number | null
  total_fluid_intake_ml: number | null

  /** Legacy free-text field, kept for backward compatibility. */
  feeding: string | null
  remarks: string | null
}

/** src/models/nss.py :: NSSData (Neonatal Sepsis Surveillance) */
export interface NSSData {
  assessment_date: string | null

  temperature: number | null
  temperature_unit: string | null
  on_radiant_warmer: boolean | null
  high_temperature_flag: boolean | null
  low_temperature_flag: boolean | null
  spo2: number | null
  pulse_rate: number | null
  tachycardia: boolean | null
  bradycardia: boolean | null
  respiratory_rate: number | null
  fast_breathing: boolean | null
  bradypnea: boolean | null
  on_noninvasive_ventilator: boolean | null
  on_invasive_ventilator: boolean | null

  cry_type: string | null
  muscle_tone: string | null
  neurological_signs: string | null
  skin_colour: string | null
  perfusion_findings: string | null
  bleeding_observed: boolean | null
  fontanelle_bulging: boolean | null
  gi_signs: string | null
  skin_umbilical_signs: string | null
  general_condition: string | null
  sepsis_impression: string | null

  blood_test_ordered: boolean | null
  blood_test_report_available: boolean | null
  tests_planned: string | null
  procalcitonin_done: boolean | null

  blood_glucose: number | null
  tlc: number | null
  hemoglobin: number | null
  platelet_count: number | null
  anc: number | null
  total_bilirubin: number | null
  crp: number | null

  /** Legacy fields, kept for backward compatibility. */
  diagnosis: string | null
  culture_result: string | null
  treatment: string | null
  outcome: string | null
  remarks: string | null
}

/** src/models/lab.py :: LabData (standalone pathology report) */
export interface LabData {
  test_date: string | null
  lab_accession_no: string | null
  collected_at: string | null
  tests_requested: string | null

  hemoglobin: number | null
  tlc: number | null
  platelet_count: number | null
  anc: number | null

  total_bilirubin: number | null
  direct_bilirubin: number | null
  indirect_bilirubin: number | null
  total_protein: number | null
  albumin: number | null
  globulin: number | null
  alkaline_phosphatase: number | null

  sodium: number | null
  potassium: number | null
  ionic_calcium: number | null
  urea: number | null
  creatinine: number | null

  crp: number | null
  remarks: string | null
}

/** src/models/sae.py :: SAEData (Serious Adverse Event) */
export interface SAEData {
  record_id: string | null
  participant_id: string | null
  site: string | null

  patient_name: string | null
  sex: string | null
  age_days: number | null
  date_of_birth: string | null

  event_date: string | null
  event_description: string | null
  diagnosis: string | null
  seriousness: string | null
  outcome: string | null
  cause_of_death: string | null

  hospital_name: string | null
  admission_date: string | null
  discharge_date: string | null

  reporter_name: string | null
  reporting_date: string | null
}

/** src/models/case_summary.py :: CaseSummary (top-level pipeline output) */
export interface CaseSummary {
  sae: SAEData | null
  maternal: MaternalData | null
  dcm: DCMData[]
  nss: NSSData[]
  lab: LabData[]

  timeline: string[]

  validation_messages: string[]
  skipped_forms: string[]

  source_pdf: string | null
  case_id: string | null
}
