"""
Neonatal Sepsis Surveillance model.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class NSSData(BaseModel):

    model_config = ConfigDict(
        extra="forbid",
        validate_assignment=True,
    )

    assessment_date: str | None = Field(default=None)

    # ------------------------
    # Vitals
    # ------------------------

    temperature: float | None = Field(default=None)

    temperature_unit: str | None = Field(default=None)

    on_radiant_warmer: bool | None = Field(default=None)

    high_temperature_flag: bool | None = Field(
        default=None,
        description="True if temp >= 38C (per form's autogenerated flag).",
    )

    low_temperature_flag: bool | None = Field(
        default=None,
        description="True if temp < 35.5C (per form's autogenerated flag).",
    )

    spo2: float | None = Field(default=None)

    pulse_rate: float | None = Field(default=None)

    tachycardia: bool | None = Field(default=None)

    bradycardia: bool | None = Field(default=None)

    respiratory_rate: float | None = Field(
        default=None,
        description="Breaths per minute. Note: source form may contain "
        "placeholder value 9999 when infant is ventilated/not assessable.",
    )

    fast_breathing: bool | None = Field(default=None)

    bradypnea: bool | None = Field(default=None)

    on_noninvasive_ventilator: bool | None = Field(default=None)

    on_invasive_ventilator: bool | None = Field(default=None)

    # ------------------------
    # Clinical exam findings
    # ------------------------

    cry_type: str | None = Field(default=None)

    muscle_tone: str | None = Field(default=None)

    neurological_signs: str | None = Field(
        default=None,
        description="e.g. convulsions, abnormal movements, arching, or None.",
    )

    skin_colour: str | None = Field(default=None)

    perfusion_findings: str | None = Field(
        default=None,
        description="e.g. CRT > 3s, delayed skin turgor, or None.",
    )

    bleeding_observed: bool | None = Field(default=None)

    fontanelle_bulging: bool | None = Field(default=None)

    gi_signs: str | None = Field(
        default=None,
        description="e.g. regurgitation, abdominal distension, or None.",
    )

    skin_umbilical_signs: str | None = Field(
        default=None,
        description="e.g. pustules, umbilicus red, jaundice, or None.",
    )

    general_condition: str | None = Field(
        default=None,
        description="e.g. Alert, Lethargic.",
    )

    sepsis_impression: str | None = Field(
        default=None,
        description="Clinician's sepsis impression: No signs of sepsis / "
        "Probable sepsis / Confirmed sepsis.",
    )

    # ------------------------
    # Blood test ordering (linkage to LabData)
    # ------------------------

    blood_test_ordered: bool | None = Field(default=None)

    blood_test_report_available: bool | None = Field(default=None)

    tests_planned: str | None = Field(
        default=None,
        description="Which tests were selected, e.g. CBC, CRP, Electrolyte Panel.",
    )

    procalcitonin_done: bool | None = Field(default=None)

    # ------------------------
    # Inline lab values (as captured directly on the NSS form,
    # separate from the standalone LAB report form)
    # ------------------------

    blood_glucose: float | None = Field(default=None)

    tlc: float | None = Field(default=None, description="Total Leucocyte Count, cells/mm3.")

    hemoglobin: float | None = Field(default=None, description="g/dL.")

    platelet_count: float | None = Field(default=None, description="lakhs/mm3.")

    anc: float | None = Field(default=None, description="Absolute Neutrophil Count, x10^3/mm3.")

    total_bilirubin: float | None = Field(default=None, description="mg/dL.")

    crp: float | None = Field(default=None, description="mg/L or mg/dL as recorded on form.")

    # ------------------------
    # Legacy / existing fields (kept for backward compatibility)
    # ------------------------

    diagnosis: str | None = Field(default=None)

    culture_result: str | None = Field(default=None)

    treatment: str | None = Field(default=None)

    outcome: str | None = Field(default=None)

    remarks: str | None = Field(default=None)
