"""
report.py

Defines the structured clinical report produced by the
AI reasoning engine.

This module contains only data models.
It has no AI, OCR or DOCX logic.
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List


@dataclass
class ClinicalReport:
    """
    Structured report generated by the reasoning engine.
    """

    executive_summary: str = ""

    maternal_history: str = ""

    clinical_timeline: List[Dict[str, Any]] = field(default_factory=list)

    daily_clinical_monitoring: List[Dict[str, Any]] = field(default_factory=list)

    neonatal_sepsis: List[Dict[str, Any]] = field(default_factory=list)

    laboratory_findings: List[Dict[str, Any]] = field(default_factory=list)

    final_outcome: str = ""

    quality_flags: List[str] = field(default_factory=list)

    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert the report into a serializable dictionary.
        """

        return {
            "executive_summary": self.executive_summary,
            "maternal_history": self.maternal_history,
            "clinical_timeline": self.clinical_timeline,
            "daily_clinical_monitoring": self.daily_clinical_monitoring,
            "neonatal_sepsis": self.neonatal_sepsis,
            "laboratory_findings": self.laboratory_findings,
            "final_outcome": self.final_outcome,
            "quality_flags": self.quality_flags,
            "metadata": self.metadata,
        }